import type {NextPage} from 'next';
import Head from 'next/head';

const Home: NextPage = () => (
	<>
		<Head>
			<title>Create Next App</title>
			<meta name='description' content='Generated by create next app' />
		</Head>

		<main>
			<h2>Static pages</h2>
		</main >
	</>
);

export default Home;
